name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: cheraghtunnel
            release_name: cheraghtunnel-linux-amd64
            use_cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_name: cheraghtunnel
            release_name: cheraghtunnel-linux-arm64
            use_cross: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.use_cross == false
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev build-essential

      - name: Build Release Binary (Standard)
        if: matrix.use_cross == false
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build Release Binary (Cross)
        if: matrix.use_cross == true
        run: |
          cargo install cross
          cross build --release --target ${{ matrix.target }}

      - name: Prepare Binary
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/${{ matrix.binary_name }} ${{ matrix.release_name }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.release_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
